# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  group: "compose-vars"
  containerSrvReg: weight-app-repo
  imageRepository: weightapprepo
  containerRegLogin: ben1213test.azurecr.io

pool: Docker

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerSrvReg)
          repository: 'weightapprepo'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  variables: 
    - group: "compose-vars"
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: staging
    displayName: Deploy to Staging
    environment:
      name: compose
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:

          - task: Docker@2
            displayName: 'Login to Registry'
            inputs:
              containerRegistry: $(containerSrvReg)
              command: 'login'

          - task: CmdLine@2
            displayName: Pull image
            inputs:
              script: ' docker pull $(containerRegLogin)/$(imageRepository):$(Build.BuildId)'

          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Azure Pass - Sponsorship(4c91c978-76e8-4500-a93a-fed14688e040)'
              azureContainerRegistry: '{"loginServer":"ben1213test.azurecr.io", "id" : "/subscriptions/4c91c978-76e8-4500-a93a-fed14688e040/resourceGroups/registry/providers/Microsoft.ContainerRegistry/registries/ben1213test"}'
              dockerComposeFile: 'docker-compose.yml'
              dockerComposeFileArgs: |
                HOST_URL = $(HOSTURL)
                OKTA_ORG_URL = $(OKTA_URL)
                OKTA_CLIENT_ID = $(OKTA_CLIENT)
                OKTA_CLIENT_SECRET =$(OKTA_SECRET)
                PGUSERNAME = $(PGUSER)
                PGPASSWORD = $(PGPASS)
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'up'
              #arguments: '-d'