# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: "compose-vars"

pool: compose

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure Pass - Sponsorship(4c91c978-76e8-4500-a93a-fed14688e040)'
    azureContainerRegistry: '{"loginServer":"ben1213test.azurecr.io", "id" : "/subscriptions/4c91c978-76e8-4500-a93a-fed14688e040/resourceGroups/registry/providers/Microsoft.ContainerRegistry/registries/ben1213test"}'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      HOST_URL = $(HOSTURL)
      OKTA_ORG_URL = $(OKTA_URL)
      OKTA_CLIENT_ID = $(OKTA_CLIENT)
      OKTA_CLIENT_SECRET =$(OKTA_SECRET)
      PGUSERNAME = $(PGUSER)
      PGPASSWORD = $(PGPASS)
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    #arguments: '-d'