# Use postgres/example user/password credentials
version: '3.1'

services:
  
  db:
    hostname: db
    container_name: wt-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_DB: postgres
      #DATABASE_URL: postgres://${PGUSER}:${PGPASS}@db:5432/postgres
    networks:
      test:
        ipv4_address: 10.5.0.5



  web:
      hostname: web
      container_name: wt-app
      build:  .     
      networks:
        test:
          ipv4_address: 10.5.0.6
      restart: always
      depends_on:
        - wt-db
      ports:
        - "8080:3000"
      environment:
        HOST: 0.0.0.0
        NODE_ENV: development
        HOST_URL: ${HOSTURL}
        COOKIE_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
        OKTA_ORG_URL: ${OKTA_URL}
        OKTA_CLIENT_ID: ${OKTA_CLIENT}
        OKTA_CLIENT_SECRET: ${OKTA_SECRET}
        PGHOST: db
        PGUSERNAME: ${PGUSER}
        PGDATABASE: postgres
        PGPASSWORD: ${PGPASS}
        #DATABASE_URL: postgres://${PGUSER}:${PGPASS}@db:5432/postgres
        PGPORT: 5432

      condition: service_healthy
      



networks:
  test:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1