# Use postgres/example user/password credentials
version: '3.1'

services:
  
  db:
    hostname: db
    container_name: wt-db
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    volumes:
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: p@ssw0rd42
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  web:
      hostname: web
      container_name: wt-app
      build:  .
      restart: always
      depends_on:
        - db
      ports:
        - "8080:8080"