# Use postgres/example user/password credentials
version: '3.1'

services:
  
  db:
    hostname: db
    container_name: wt-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_DB: postgres
    
  web:
      hostname: web
      container_name: wt-app
      build:  . 
      restart: always
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        PORT: 8080
        HOST: 0.0.0.0
        NODE_ENV: development
        HOST_URL: ${HOSTURL}
        COOKIE_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
        OKTA_ORG_URL: ${OKTA_URL}
        OKTA_CLIENT_ID: ${OKTA_CLIENT}
        OKTA_CLIENT_SECRET: ${OKTA_SECRET}
        PGHOST: db
        PGUSERNAME: ${PGUSER}
        PGDATABASE: postgres
        PGPASSWORD: ${PGPASS}
        PGPORT: 5432